apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: n3
spec:
  attachmentType: vlan
  cniType: sriov
  ipFamilyPolicy: dualstack
  networkInstance:
    name: default
status:
  ipClaimStatus: []
