apiVersion: v1
kind: ConfigMap
metadata:
  name: namespaceNetworkSystem
  annotations:
    kerraform/config: true
data:
  spec:
  - resource:
      kubernetes_manifest:
        network-system:
          apiVersion: v1
          kind: Namespace
          object:
            metadata:
              name: network-system