apiVersion: v1
kind: ConfigMap
metadata:
  name: vxlanIndex
  annotations:
    kerraform/config: true
data:
  spec:
  - variable:
      clusterName:
        attributes:
          default: clusterName
  - resource:
      resource-backend_vxlanclaim:
        vxlanrange:
          object:
            apiVersion: nephio.org/v1alpha1
            kind: VXLANClaim
            metadata:
              name: $var.clusterName
              annotations:
                config.kubernetes.io/local-config: "true"
            spec:
              vxlanindex: global
              range: block:65536
  - resource:
      kubernetes_manifest:
        wirer:
          attributes:
            provider: kubernetes.local
          object:
            apiVersion: vxlan.resource.nephio.org/v1alpha1
            kind: VXLANIndex
            metadata:
              namespace: network-system
            spec:
              maxEntryID: 65536 + $kubernetes_req_nephio_org_v1alpha1_vxlanclaim.vxlanrange.status.offset
              offset: $kubernetes_req_nephio_org_v1alpha1_vxlanclaim.vxlanrange.status.offset