version: 1

before:
  hooks:
    - go mod tidy
    - go mod download
    #- go generate ./...

builds:
- id: kform
  main: tools/cmd/kform/main.go
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    #- freebsd
    - linux
    #- openbsd
    #- windows
  goarch:
    #- '386'
    - amd64
    #- arm
    - arm64
  ignore:
    - goarch: arm
      goos: windows
    - goarch: arm64
      goos: freebsd
    - goarch: arm64
      goos: windows
    - goarch: arm64
      goos: openbsd
  mod_timestamp: '{{ .CommitTimestamp }}'
archives:
- name_template: >-
    {{- .ProjectName }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end }}
    {{- if .Arm }}v{{ .Arm }}{{ end -}}
  format_overrides:
  - goos: windows
    format: zip
  builds_info:
    group: root
    owner: root
  files:
  - none*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
