apiVersion: v1
kind: ConfigMap
metadata:
  name: main
  annotations:
    kform/config: true
data:
  spec:
  - resource:
      resourcebackend_vxlanclaim:
        vxlanrange:
          attributes:
            schema:
              apiVersion: nephio.org/v1alpha1
              kind: VXLANClaim
          instances:
          - metadata:
            name: $var.context.data.clusterName
            spec:
              vxlanindex: global
              range: block:65536
  - resource:
      kubernetes_manifest:
        vxlanindex:
          attributes:
            provider: kubernetes.local
            schema:
              apiVersion: vxlan.resource.nephio.org/v1alpha1
              kind: VXLANIndex
          instances: 
          - metadata:
              name: $var.context.data.app
              namespace: network-system
            spec:
              maxEntryID: 65536 + $resourcebackend_vxlanclaim.vxlanrange.status.offset
              offset: $resourcebackend_vxlanclaim.vxlanrange.status.offset