apiVersion: v1
kind: ConfigMap
metadata:
  name: variables
  annotations:
    kform/config: true
data:
  spec:
  - input:
      context:
        attributes:
          schema:
            apiVersion: v1
            kind: ConfigMap
        default:
        - metadata:
            name: context
          data:
            app: wirer
            clusterName: dummy
            package: url-blabla