apiVersion: v1
kind: ConfigMap
metadata:
  name: main
  annotations:
    kform/config: true
data:
  spec:
  - resource:
      fetch_package:
        pkg:
          attributes:
            schema:
              apiVersion: sw.nephio.org/v1alpha1
              kind: Package
            validation: dynamic
          instances:
          - metadata:
              name: wirer
            spec:
              url: "https://github.com/.../wirer-incluster" ## this parameter is location dependent