apiVersion: v1
kind: ConfigMap
metadata:
  name: outputs
  annotations:
    kform/config: true
data:
  spec:
  - output:
      wirerPkg:
        attributes:
          schema:
            apiVersion: sw.nephio.org/v1alpha1
            kind: Package
          validation: dynamic
          for_each: $fetch_package.pkg
        instances: 
          [value: $each.value]
