apiVersion: v1
kind: ConfigMap
metadata:
  name: main
  annotations:
    kform/config: true
data:
  spec:
  - resource:
      resourcebackend_ipclaim:
        this:
          attributes:
            schema:
              apiVersion: ipam.resource.nephio.org/v1alpha1
              kind: IPClaim
            forEach: $input.dnn[0].spec.pools
          instances: 
          - metadata:
              name: $input.dnn[0].metadata.name + "-" + $each.value.spec.pool[0]
            spec:
              kind: pool
              selector:
                matchLabels:
                  nephio.org/address-family: $input.dnn[0].spec.ipFamily
                  nephio.org/cluster-name: $input.context.data.clusterName
              createPrefix: true
              networkInstance:  
                name: $input.dnn[0].spec.networkInstance.name
              prefixLength: $each.value.prefixLength

          
          
        