apiVersion: v1
kind: ConfigMap
metadata:
  name: main
  annotations:
    kform/config: true
data:
  spec:
  - resource:
      resource-backend_ipclaim:
        this:
          attributes:
            for_each: $var.dnn[0].spec.pools
          data: 
          - apiVersion: ipam.resource.nephio.org/v1alpha1
            kind: IPClaim
            metadata:
              name: $var.dnn[0].metadata.name + "-" + $each.value.spec.pool[0]
            spec:
              kind: pool
              selector:
                matchLabels:
                  nephio.org/address-family: $var.dnn[0].spec.ipFamily
                  nephio.org/cluster-name: $var.context.data.clusterName
              createPrefix: true
              networkInstance:  
                name: $var.dnn[0].spec.networkInstance.name
              prefixLength: $each.value.prefixLength
  - local:
      pools:
        attributes:
          for_each: $resource.resource-backend_ipclaim
        data:
          
          
        