apiVersion: v1
kind: ConfigMap
metadata:
  name: outputs
  annotations:
    kform/config: true
data:
  spec:
  - output:
      dnn:
        attributes:
          for_each: $resource-backend_ipclaim.this
        data:
        - apiVersion: req.nephio.org/v1alpha1
          kind: DataNetwork
          metadata: $var.dnn[0]
          spec: $var.dnn[0]
          status: 
            pools: 
            - name: $each.value.metadata.name
              ipClaim: 
                prefix: $each.value.status.prefix
                
              
          
          