apiVersion: v1
kind: ConfigMap
metadata:
  name: outputs
  annotations:
    kform/config: true
data:
  spec:
  - output:
      dnn:
        attributes:
          schema:
            apiVersion: req.nephio.org/v1alpha1
            kind: DataNetwork
          forEach: $resourcebackend_ipclaim.this
        value:
          metadata: "$input.dnn[0]"
          spec: "$input.dnn[0]"
          status: 
            pools: 
            - name: $each.value.metadata.name
              ipClaim: 
                prefix: $each.value.status.prefix
                
              
          
          