apiVersion: v1
kind: ConfigMap
metadata:
  name: variables
  annotations:
    kform/config: true
data:
  spec:
  - variable:
      context:
        data:
        - apiVersion: v1
          kind: ConfigMap
          metadata:
            name: variables
          data:
            clusterName: dummy
  - variable:
      dnn:
        data:
        - apiVersion: req.nephio.org/v1alpha1
          kind: DataNetwork
          metadata:
            name: dummy
    