apiVersion: v1
kind: ConfigMap
metadata:
  name: outputs
  annotations:
    kform/config: true
data:
  spec:
  - output:
      metallbPool:
        schema:
            apiVersion: metallb.io/v1beta1
            kind: IPAddressPool
        attributes:
          for_each: $kubernetes_manifest.metallbPool
        instances:
          - $each.value