apiVersion: req.nephio.org/v1alpha1
kind: DataNetwork
metadata:
  name: dummy
spec:
  networkInstance:
    name: vpc-internet
  pools:
  - ipFamily: ipv4
    name: pool1
    prefixLength: 8
status:
  pools:
  - ipClaim:
      prefix: 172.0.0.0/8
    name: pool1
