apiVersion: v1
kind: ConfigMap
metadata:
  name: input
  annotations:
    kform/config: true
data:
  spec:
  - input:
      context:
        attributes:
          schema:
            apiVersion: v1
            kind: ConfigMap
        default:
        - metadata:
            name: context
          data:
            clusterName: dummy
  - input:
      dnn:
        attributes:
          schema:
            apiVersion: req.nephio.org/v1alpha1
            kind: DataNetwork
        default:
        - metadata:
            name: dummy
          spec:
            networkInstance:
              name: vpc-internet
            pools:
              - name: pool1
                prefixLength: 8
                ipFamily: ipv4