apiVersion: meta.pkg.kform.io/v1alpha1
kind: KformFile
metadata:
  name: dnn
spec:
  kind: module
  providerRequirements:
    kubernetes:
      #source: github.com/henderiw-nephio/kform
      source: ghcr.io/kform-providers/kubernetes
      version: "0.0.1"
    resourcebackend:
      #source: github.com/henderiw-nephio/kform
      source: ghcr.io/kform-providers/resourcebackend
      version: "0.0.1"
  info: {}
