apiVersion: v1
kind: ConfigMap
metadata:
  name: outputs
  annotations:
    kform/config: true
data:
  spec:
  - output:
      dnn:
        attributes:
          schema:
            apiVersion: req.nephio.org/v1alpha1
            kind: DataNetwork
        value:
          metadata: $input.dnn[0].metadata
          spec: $input.dnn[0].spec
          status: 
            pools: 
            - name: $resourcebackend_ipclaim.this[0].metadata.name
              ipClaim: 
                prefix: $resourcebackend_ipclaim.this[0].status.prefix