apiVersion: v1
kind: ConfigMap
metadata:
  name: outputs
  annotations:
    kform/config: true
data:
  spec:
  - output:
      interface:
        attributes:
          schema:
            apiVersion: req.nephio.org/v1alpha1
            kind: Interface
        value: [$resourcebackend_ipclaim.ipv4, $resourcebackend_ipclaim.ipv6, $resourcebackend_vlanclaim.vlan]