apiVersion: v1
kind: ConfigMap
metadata:
  name: outputs
  annotations:
    kform/config: true
data:
  spec:
  - output:
      interface:
        attributes:
          schema:
            apiVersion: req.nephio.org/v1alpha1
            kind: Interface
        #value: [$resourcebackend_ipclaim.ipv4, $resourcebackend_ipclaim.ipv6, $resourcebackend_vlanclaim.vlan]
        value:
          metadata: $input.interface[0].metadata
          spec: $input.interface[0].spec
          status:
            vlanClaimStatus: $resourcebackend_vlanclaim.vlan[0].status
            ipClaimStatus:
            - $resourcebackend_ipclaim.ipv4[0].status
            - $resourcebackend_ipclaim.ipv6[0].status