apiVersion: v1
kind: ConfigMap
metadata:
  name: providers
  annotations:
    kform/config: true
data:
  spec:
  - provider:
      kubernetes:
        attributes:
          schema:
            apiVersion: kubernetes.provider.kform.io
            kind: ProviderConfig
        config: 
          metadata:
            name: kubernetes
          spec:
            kind: package
            directory: ./examples/out       
  - provider:
      resourcebackend:
        attributes:
          schema:
            apiVersion: resourcebackend.provider.kform.io
            kind: ProviderConfig
        config: 
          metadata:
            name: resourcebackend
          spec:
            kind: mock
  - provider:
      test:
        attributes:
          schema:
            apiVersion: dummy.provider.kform.io
            kind: ProviderConfig
        config: 
          metadata:
            name: dummy
        