apiVersion: v1
kind: ConfigMap
metadata:
  name: outputs
  annotations:
    kform/config: true
data:
  spec:
  - output:
      nad:
        attributes:
          schema:
            apiVersion: k8s.cni.cncf.io/v1
            kind: NetworkAttachmentDefinition
        instances: ['[$input.nad, $input.ipClaimIPv4, $input.ipClaimIPv6, $input.vlanClaim].nad-fn']
                
              
          
          