apiVersion: v1
kind: ConfigMap
metadata:
  name: input
  annotations:
    kform/config: true
data:
  spec:
  - input:
      context:
        data:
        - apiVersion: v1
          kind: ConfigMap
  - input:
      interface:
        data:
        - apiVersion: req.nephio.org/v1alpha1
          kind: Interface
          metadata:
            name: dummy
    