apiVersion: v1
kind: ConfigMap
metadata:
  name: outputs
  annotations:
    kform/config: true
data:
  spec:
  - output:
      nad:
        attributes:
          schema:
            apiVersion: k8s.cni.cncf.io/v1
            kind: NetworkAttachmentDefinition
        value: $module.nad.nad
  - output:
      interface:
        attributes:
          forEach: $resourcebackend_ipclaim.ipv4
          schema:
            apiVersion: req.nephio.org/v1alpha1
            kind: Interface
        value:
          metadata: $input.interface[0]
          spec: $input.interface[0]
          status:
            vlanClaimStatus: 
            ipClaimStatus: concat($resourcebackend_ipclaim.ipv4, $resourcebackend_ipclaim.ipv6)
          