---
name: goreleaser ci
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      goreleaser: ${{ steps.filter.outputs.goreleaser }}
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: setup go
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: go.mod
      - name: run go releaser
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}