name: test

on:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
    - name: github repo 
      run: echo ${{ github.repository }}
    - name: github ref
      run: echo ${{ github.ref}}
    - name: github ref
      run: echo ${{ github.ref_name}}